import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "./config/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Leather Store</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {children}
      </body>
    </html>
  );
}
